# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  # docker: circleci/docker@1.5.0
  # go: circleci/go@1.4.0
  # gke: circleci/gcp-gke@1.1.0
  # gcr: circleci/gcp-gcr@0.11.0
  heroku: circleci/heroku@1.2.5
jobs:
  test:
    docker:
      # specify the version
      - image: circleci/golang:1.15
        auth:
          username: thegbemiga
          password: $DOCKERHUB_PASSWORD 
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Fetch dependencies and Run Tests
          command: |
            go get -v -t -d ./...
            go build .
            go test -v ./...
     
  deploy:
    description: Deploy api to Heroku
    machine: true
    steps:
      - checkout

      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a outdoor-api web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a outdoor-api web
     
workflows:
  test_update_deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main

      # - dockerize:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - main

      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main