# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  # docker: circleci/docker@1.5.0
  # go: circleci/go@1.4.0
  gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.11.0
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15
        auth:
          username: thegbemiga
          password: $DOCKERHUB_PASSWORD 
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Fetch dependencies and Run Tests
          command: |
            go get -v -t -d ./...
            go build .
            go test -v ./...
  
  dockerize:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: outdoorsapi
          tag: "v1"
      - gcr/push-image:
          image: outdoorsapi
          tag: "v1"
     
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install gcloud and `kubectl` if not already installed.
      - gke/install
      # initialize the gcloud CLI
      # - gke/init
      # Update a deployment Docker image.
      - gke/rollout-image:
          cluster: cluster-1
          deployment: outdoorsapi
          container: outdoors-backend
          image: gcr.io/outdoors-293920/outdoorsapi:v1
workflows:
  build_update_deploy:
    jobs:
      - build
      - dockerize:
          requires:
            - build
      - deploy:
          requires:
            - dockerize