---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "outdoorsapi"
  namespace: "default"
  labels:
    app: "outdoorsapi"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "outdoorsapi"
  template:
    metadata:
      labels:
        app: "outdoorsapi"
    spec:
      containers:
      - name: "outdoorsapi"
        image: "gcr.io/outdoors-293920/outdoorsapi@sha256:b878047b330c284bf00af211ef94fff1e49cff04047ed6158b8ea4934b17f25a"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "outdoorsapi-hpa-armr"
  namespace: "default"
  labels:
    app: "outdoorsapi"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "outdoorsapi"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
